name:  Publish package to Maven Repo
on:
  release:
    types: [created]
jobs:
  publish:
    name: 🎉 Publish to Maven Repo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🔨 Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: 🏗️ Publish package
        run: gradle publish
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}